
const cityData = [
  { name: "Mumbai", code: "BOM" },
  { name: "Delhi", code: "DEL" },
  { name: "Bangalore", code: "BLR" },
  { name: "Hyderabad", code: "HYD" },
  { name: "Chennai", code: "MAA" },
  { name: "Kolkata", code: "CCU" },
  { name: "Ahmedabad", code: "AMD" },
  { name: "Pune", code: "PNQ" },
  { name: "Jaipur", code: "JAI" },
  { name: "Surat", code: "STV" },
  { name: "Lucknow", code: "LKO" },
  { name: "Kanpur", code: "KNU" },
  { name: "Nagpur", code: "NAG" },
  { name: "Indore", code: "IDR" },
  { name: "Bhopal", code: "BHO" },
  { name: "Patna", code: "PAT" },
  { name: "Vadodara", code: "BDQ" },
  { name: "Ludhiana", code: "LUH" },
  { name: "Agra", code: "AGR" },
  { name: "Varanasi", code: "VNS" },
  { name: "Goa", code: "GOI" },
  { name: "Coimbatore", code: "CJB" },
  { name: "Kochi", code: "COK" },
  { name: "Trivandrum", code: "TRV" },
  { name: "Guwahati", code: "GAU" },
  { name: "Bhubaneswar", code: "BBI" },
  { name: "Amritsar", code: "ATQ" },
  { name: "Chandigarh", code: "IXC" },
  { name: "Dehradun", code: "DED" },
  { name: "Ranchi", code: "IXR" },
  { name: "Raipur", code: "RPR" },
  { name: "Visakhapatnam", code: "VTZ" },
  { name: "Tiruchirappalli", code: "TRZ" },
  { name: "Madurai", code: "IXM" },
  { name: "Mangalore", code: "IXE" },
  { name: "Vijayawada", code: "VGA" },
  { name: "Rajkot", code: "RAJ" },
  { name: "Jodhpur", code: "JDH" },
  { name: "Udaipur", code: "UDR" },
  { name: "Leh", code: "IXL" },
  { name: "Srinagar", code: "SXR" },
  { name: "Jammu", code: "IXJ" },
  { name: "Imphal", code: "IMF" },
  { name: "Agartala", code: "IXA" },
  { name: "Shillong", code: "SHL" },
  { name: "Aizawl", code: "AJL" },
  { name: "Dimapur", code: "DMU" },
  { name: "Silchar", code: "IXS" },
  { name: "Dibrugarh", code: "DIB" },
  { name: "Jorhat", code: "JRH" },
  { name: "Port Blair", code: "IXZ" },
  { name: "Belgaum", code: "IXG" },
  { name: "Hubli", code: "HBX" },
  { name: "Aurangabad", code: "IXU" },
  { name: "Kolhapur", code: "KLH" },
  { name: "Nashik", code: "ISK" },
  { name: "Shirdi", code: "SAG" },
  { name: "Gwalior", code: "GWL" },
  { name: "Jabalpur", code: "JLR" },
  { name: "Allahabad", code: "IXD" },
  { name: "Gorakhpur", code: "GOP" },
  { name: "Bareilly", code: "BEK" },
  { name: "Bhagalpur", code: "BGP" },
  { name: "Gaya", code: "GAY" },
  { name: "Darbhanga", code: "DBR" },
  { name: "Jamshedpur", code: "IXW" },
  { name: "Durgapur", code: "RDP" },
  { name: "Siliguri", code: "IXB" },
  { name: "Cooch Behar", code: "COH" },
  { name: "Bhavnagar", code: "BHU" },
  { name: "Jamnagar", code: "JGA" },
  { name: "Kandla", code: "IXY" },
  { name: "Bhuj", code: "BHJ" },
  { name: "Porbandar", code: "PBD" },
  { name: "Diu", code: "DIU" },
  { name: "Keshod", code: "IXK" },
  { name: "Pondicherry", code: "PNY" },
  { name: "Salem", code: "SXV" },
  { name: "Tuticorin", code: "TCR" },
  { name: "Neyveli", code: "NVY" },
  { name: "Hosur", code: "HOX" },
  { name: "Bellary", code: "BEP" },
  { name: "Mysore", code: "MYQ" },
  { name: "Kozhikode", code: "CCJ" },
  { name: "Kannur", code: "CNN" },
  { name: "Thiruvananthapuram", code: "TRV" },
  { name: "Kottayam", code: "KTY" },
  { name: "Agatti Island", code: "AGX" },
  { name: "Kullu", code: "KUU" },
  { name: "Shimla", code: "SLV" },
  { name: "Dharamshala", code: "DHM" },
  { name: "Pathankot", code: "IXP" },
  { name: "Bhatinda", code: "BUP" },
  { name: "Sahnewal", code: "LUH" },
  { name: "Pantnagar", code: "PGH" },
  { name: "Pithoragarh", code: "NNS" },
  { name: "Jaisalmer", code: "JSA" },
  { name: "Kota", code: "KTU" },
  { name: "Kishangarh", code: "KQH" },
  { name: "Bikaner", code: "BKB" },
  { name: "Jharsuguda", code: "JRG" },
  { name: "Rourkela", code: "RRK" },
  { name: "Jeypore", code: "PYB" },
  { name: "Vishakhapatnam", code: "VTZ" },
  { name: "Rajahmundry", code: "RJA" },
  { name: "Tirupati", code: "TIR" },
  { name: "Kadapa", code: "CDP" },
  { name: "Warangal", code: "WGC" },
  { name: "Nanded", code: "NDC" },
  { name: "Solapur", code: "SSE" },
  { name: "Gulbarga", code: "GBI" },
  { name: "Bidar", code: "IXX" },
  { name: "Sholapur", code: "SSE" },
  { name: "Latur", code: "LTU" },
  { name: "Nanded", code: "NDC" },
  { name: "Akola", code: "AKD" },
  { name: "Gondia", code: "GDB" },
  { name: "Jalgaon", code: "JLQ" },
  { name: "Nandurbar", code: "NDB" },
  { name: "Ratnagiri", code: "RTC" },
  { name: "Sindhudurg", code: "SDW" }
];

const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

const indianAirports = [
  "Indira Gandhi International Airport (Delhi)",
  "Chhatrapati Shivaji Maharaj International Airport (Mumbai)",
  "Kempegowda International Airport (Bengaluru)",
  "Netaji Subhas Chandra Bose International Airport (Kolkata)",
  "Chennai International Airport (Chennai)",
  "Rajiv Gandhi International Airport (Hyderabad)",
  "Sardar Vallabhbhai Patel International Airport (Ahmedabad)",
  "Cochin International Airport (Kochi)",
  "Mangaluru International Airport (Mangaluru)",
  "Goa International Airport (Dabolim)",
  "Pune International Airport (Pune)",
  "Jaipur International Airport (Jaipur)",
  "Lucknow International Airport (Lucknow)",
  "Chandigarh International Airport (Chandigarh)",
  "Thiruvananthapuram International Airport (Thiruvananthapuram)",
  "Srinagar International Airport (Srinagar)",
  "Madurai International Airport (Madurai)",
  "Vadodara Airport (Vadodara)",
  "Surat International Airport (Surat)",
  "Bhopal Raja Bhoj Airport (Bhopal)",
  "Indore Devi Ahilyabai Holkar Airport (Indore)",
  "Nagpur Dr. Babasaheb Ambedkar International Airport (Nagpur)",
  "Gaya International Airport (Gaya)",
  "Visakhapatnam International Airport (Visakhapatnam)",
  "Dibrugarh Airport (Dibrugarh)",
  "Guwahati Lokpriya Gopinath Bordoloi International Airport (Guwahati)",
  "Mysuru Airport (Mysuru)",
  "Rajkot Airport (Rajkot)",
  "Bagdogra International Airport (Siliguri)",
  "Agartala Maharaja Bir Bikram Airport (Agartala)",
  "Imphal Tulihal Airport (Imphal)",
  "Shillong Umroi Airport (Shillong)",
  "Bhubaneswar Biju Patnaik International Airport (Bhubaneswar)",
  "Ranchi Birsa Munda Airport (Ranchi)",
  "Udaipur Maharana Pratap Airport (Udaipur)",
  "Aurangabad Chikkalthana Airport (Aurangabad)",
  "Jammu Satwari Airport (Jammu)"
];

const indianRailwayStations = [
  "Howrah Junction (Kolkata, West Bengal)",
  "Sealdah Railway Station (Kolkata, West Bengal)",
  "Chhatrapati Shivaji Maharaj Terminus (Mumbai, Maharashtra)",
  "Mumbai Lokmanya Tilak Terminus (Mumbai, Maharashtra)",
  "Pune Junction (Pune, Maharashtra)",
  "New Delhi Railway Station (New Delhi, Delhi)",
  "Hazrat Nizamuddin Railway Station (New Delhi, Delhi)",
  "Chennai Central (Chennai, Tamil Nadu)",
  "Chennai Egmore (Chennai, Tamil Nadu)",
  "Coimbatore Junction (Coimbatore, Tamil Nadu)",
  "Bengaluru City Junction (Bengaluru, Karnataka)",
  "Yesvantpur Junction (Bengaluru, Karnataka)",
  "Hyderabad Deccan (Hyderabad, Telangana)",
  "Secunderabad Junction (Hyderabad, Telangana)",
  "Ahmedabad Junction (Ahmedabad, Gujarat)",
  "Surat Railway Station (Surat, Gujarat)",
  "Vadodara Junction (Vadodara, Gujarat)",
  "Jaipur Junction (Jaipur, Rajasthan)",
  "Udaipur City Railway Station (Udaipur, Rajasthan)",
  "Patna Junction (Patna, Bihar)",
  "Gaya Junction (Gaya, Bihar)",
  "Lucknow Charbagh (Lucknow, Uttar Pradesh)",
  "Kanpur Central (Kanpur, Uttar Pradesh)",
  "Varanasi Junction (Varanasi, Uttar Pradesh)",
  "Bhopal Junction (Bhopal, Madhya Pradesh)",
  "Indore Junction (Indore, Madhya Pradesh)",
  "Bhubaneswar Railway Station (Bhubaneswar, Odisha)",
  "Cuttack Railway Station (Cuttack, Odisha)",
  "Ranchi Junction (Ranchi, Jharkhand)",
  "Dhanbad Junction (Dhanbad, Jharkhand)",
  "Guwahati Junction (Guwahati, Assam)",
  "Dibrugarh Railway Station (Dibrugarh, Assam)",
  "Jammu Tawi (Jammu, Jammu & Kashmir)",
  "Srinagar Railway Station (Srinagar, Jammu & Kashmir)",
  "Chandigarh Junction (Chandigarh)",
  "Amritsar Junction (Amritsar, Punjab)",
  "Patiala Junction (Patiala, Punjab)",
  "Kochi Ernakulam Junction (Kochi, Kerala)",
  "Kochi Harbour Terminus (Kochi, Kerala)",
  "Madurai Junction (Madurai, Tamil Nadu)",
  "Visakhapatnam Junction (Visakhapatnam, Andhra Pradesh)",
  "Vijayawada Junction (Vijayawada, Andhra Pradesh)",
  "Agartala Railway Station (Agartala, Tripura)",
  "Silchar Railway Station (Silchar, Assam)",
  "Dehradun Railway Station (Dehradun, Uttarakhand)",
  "Shimla Railway Station (Shimla, Himachal Pradesh)",
  "Panaji Railway Station (Madgaon, Goa)",
  "Itarsi Junction (Itarsi, Madhya Pradesh)",
  "Raipur Junction (Raipur, Chhattisgarh)"
];


const hotelData = [
  "Grand Hyatt", "Marriott", "Hilton", "InterContinental",
  "Four Seasons", "Ritz-Carlton", "Sheraton", "Westin"
];

const vehicleTypes = ["Car", "Bike", "Van", "SUV"];

export { indianAirports, indianRailwayStations, indianStates, cityData, hotelData, vehicleTypes };